In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

broadcasting in python


In [2]:
import numpy as np
a = np.random.randn(5)

In [3]:
print(a)

[-0.2501171   0.33417434 -0.40167316 -0.31586873 -0.95625708]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.2501171   0.33417434 -0.40167316 -0.31586873 -0.95625708]


In [6]:
print(np.dot(a, a.T))

1.3497730316824599


In [7]:
a = np.random.randn(5,1)

In [8]:
print(a)

[[ 0.7833247 ]
 [-1.60307173]
 [-0.30029457]
 [-0.77933974]
 [-0.2977246 ]]


In [9]:
print(a.T)

[[ 0.7833247  -1.60307173 -0.30029457 -0.77933974 -0.2977246 ]]


In [10]:
print(np.dot(a, a.T))

[[ 0.61359759 -1.25572569 -0.23522816 -0.61047607 -0.23321503]
 [-1.25572569  2.56983898  0.48139374  1.24933751  0.47727388]
 [-0.23522816  0.48139374  0.09017683  0.2340315   0.08940508]
 [-0.61047607  1.24933751  0.2340315   0.60737044  0.23202861]
 [-0.23321503  0.47727388  0.08940508  0.23202861  0.08863994]]


In [11]:
a = np.random.randn(4,3)
b = np.random.randn(1,3)
c = a *b

        
print(c.shape)


(4, 3)
